# Generated by Django 5.2.1 on 2025-05-19 23:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Relatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('url_origem', models.URLField()),
                ('tipo', models.CharField(choices=[('pdf', 'PDF'), ('excel', 'Excel'), ('csv', 'CSV'), ('html', 'HTML')], max_length=10)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('baixado', 'Baixado'), ('processado', 'Processado'), ('erro', 'Erro')], default='pendente', max_length=20)),
                ('arquivo', models.FileField(blank=True, null=True, upload_to='relatorios/')),
                ('tamanho_arquivo', models.IntegerField(blank=True, null=True)),
                ('tipo_conteudo', models.CharField(blank=True, max_length=100, null=True)),
                ('baixado_em', models.DateTimeField(blank=True, null=True)),
                ('processado_em', models.DateTimeField(blank=True, null=True)),
                ('ultima_verificacao', models.DateTimeField(blank=True, null=True)),
                ('mensagem_erro', models.TextField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DadosExtraidos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_conteudo', models.CharField(max_length=50)),
                ('conteudo', models.TextField()),
                ('numero_pagina', models.IntegerField(blank=True, null=True)),
                ('numero_linha', models.IntegerField(blank=True, null=True)),
                ('nome_planilha', models.CharField(blank=True, max_length=100, null=True)),
                ('numero_tabela', models.IntegerField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('relatorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dados_extraidos', to='documentos.relatorio')),
            ],
        ),
        migrations.CreateModel(
            name='AnaliseTexto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origem', models.CharField(max_length=100)),
                ('entidades', models.TextField()),
                ('texto_original', models.TextField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('relatorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analises', to='documentos.relatorio')),
            ],
        ),
    ]
